import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
const MAX_EVENTS=5000;
const DISCOVERY=new Set(['initialize','notifications/initialized','tools/list','ping','resources/list','resources/templates/list','prompts/list']);
const INTERNAL_RE=/(github-actions|curl|railway|healthcheck|recover-registry-check)/i;
const KNOWN_VALIDATOR_RE=/(smithery|glama|pulsemcp|mcp[- ]?registry|registry\.modelcontextprotocol|modelcontextprotocol.*registry|recover-registry-check)/i;
const INTERACTIVE_CLIENT_RE=/(claude|cursor|windsurf|vscode|visual studio code|chatgpt|openai|cline|roo|zed)/i;
function dataDir(){return process.env.RECOVER_DATA_DIR??(process.env.RAILWAY_ENVIRONMENT?'/data':path.resolve('.recover-data'))}
function hash(v){return crypto.createHash('sha256').update(String(v||'unknown')).digest('hex').slice(0,12)}
function atomic(file,data){fs.mkdirSync(path.dirname(file),{recursive:true});const t=`${file}.${process.pid}.tmp`;fs.writeFileSync(t,JSON.stringify(data),{mode:0o600});fs.renameSync(t,file)}
function safe(v,max=256){const s=String(v||'').trim();return s?s.slice(0,max):null}
function internal(req){return String(req.headers['x-recover-internal']||'')==='1'||INTERNAL_RE.test(String(req.headers['user-agent']||''))}
function source(req){const explicit=safe(req.headers['x-recover-source'],64);if(explicit)return explicit;return /modelcontextprotocol|mcp/i.test(String(req.headers['user-agent']||''))?'mcp-client':'direct'}
function isDiscovery(e){return e.kind==='mcp'&&DISCOVERY.has(e.route)}
function isReal(e){return e.external&&(e.kind==='recover'||(e.kind==='mcp'&&e.route==='tools/call:recover_decide'))}
function evidenceText(e){return [e.audit?.userAgent,e.audit?.clientInfo?.name,e.audit?.clientInfo?.version,e.audit?.origin,e.audit?.referrer,e.audit?.via,e.source].filter(Boolean).join(' ')}
function classify(e,discoveryAt){
 if(!e.external)return {classification:'CONTROLLED_TEST',reasons:['internal/test marker']};
 if(!isReal(e))return {classification:null,reasons:[]};
 const text=evidenceText(e);
 if(KNOWN_VALIDATOR_RE.test(text))return {classification:'KNOWN_VALIDATOR',reasons:['known registry/directory/validator evidence']};
 const delay=discoveryAt==null?null:Math.max(0,new Date(e.at).getTime()-discoveryAt);
 const client=e.audit?.clientInfo?.name||'';
 if(INTERACTIVE_CLIENT_RE.test(client)&&!KNOWN_VALIDATOR_RE.test(text))return {classification:'CREDIBLE_REAL_USE',reasons:[`interactive MCP client: ${client}`,...(delay==null?[]:[`discovery-to-core ${delay}ms`])]};
 if(e.kind==='recover'&&e.source==='direct')return {classification:'UNKNOWN_MACHINE',reasons:['direct core call but caller identity is not independently attributable']};
 if(delay!=null&&delay<=15000)return {classification:'LIKELY_VALIDATOR',reasons:[`discovery-to-core only ${delay}ms`,'no interactive client evidence']};
 return {classification:'UNKNOWN_MACHINE',reasons:['core tool invoked','insufficient evidence to prove genuine stranger']};
}
export class ActivityStore{
 constructor({dir=null}={}){this.dir=dir??dataDir();this.file=path.join(this.dir,'activity.json');this.realFile=path.join(this.dir,'real-use.json');this.persistent=Boolean(dir||process.env.RECOVER_DATA_DIR||process.env.RAILWAY_ENVIRONMENT);this.events=[];this.real=[];this.firstSeen=new Map();this.discoverySeen=new Map();this.clientInfo=new Map();if(this.persistent)this.load()}
 load(){try{const d=JSON.parse(fs.readFileSync(this.file,'utf8'));this.events=d.events||[];this.firstSeen=new Map(d.firstSeen||[]);this.discoverySeen=new Map(d.discoverySeen||[]);this.clientInfo=new Map(d.clientInfo||[])}catch{}try{const d=JSON.parse(fs.readFileSync(this.realFile,'utf8'));this.real=d.events||[]}catch{}this.reconstruct()}
 reconstruct(){let changed=false;const ids=new Set(this.real.map(e=>e.id));for(const e of this.events){if(isReal(e)&&!ids.has(e.id)){this.real.push(e);ids.add(e.id);changed=true}}for(const e of this.real){if(!e.auditVersion){e.auditVersion=2;e.classification='UNKNOWN_MACHINE';e.classificationReasons=['historical event predates auditable evidence envelope'];changed=true}}this.real.sort((a,b)=>a.at.localeCompare(b.at));if(changed)this.persistReal()}
 persist(){if(this.persistent)atomic(this.file,{events:this.events,firstSeen:[...this.firstSeen],discoverySeen:[...this.discoverySeen],clientInfo:[...this.clientInfo]})}
 persistReal(){if(this.persistent)atomic(this.realFile,{version:2,events:this.real})}
 record(req,{kind,route=null,decision=null,status=200,clientInfo=null}={}){const ip=String(req.headers['x-forwarded-for']||'').split(',')[0].trim()||req.socket?.remoteAddress||'';const caller=hash([ip,req.headers['user-agent']||'',req.headers['accept-language']||''].join('|'));const seen=this.firstSeen.has(caller);if(!seen)this.firstSeen.set(caller,Date.now());if(clientInfo?.name)this.clientInfo.set(caller,{name:safe(clientInfo.name,80),version:safe(clientInfo.version,40)});const ci=this.clientInfo.get(caller)||null;const event={id:crypto.randomUUID(),at:new Date().toISOString(),kind,route,decision,status,source:source(req),channel:kind==='mcp'?'mcp':'rest',caller,callerState:seen?'returning':'new',external:!internal(req),auditVersion:2,audit:{userAgent:safe(req.headers['user-agent'],512),acceptLanguage:safe(req.headers['accept-language'],128),origin:safe(req.headers.origin,256),referrer:safe(req.headers.referer||req.headers.referrer,256),via:safe(req.headers.via,128),forwardedHost:safe(req.headers['x-forwarded-host'],128),requestMethod:safe(req.method,16),requestPath:safe(req.url,128),clientInfo:ci}};event.discovery=isDiscovery(event);if(event.discovery&&!this.discoverySeen.has(caller))this.discoverySeen.set(caller,Date.now());event.realUse=isReal(event);event.convertedFromDiscovery=event.realUse&&this.discoverySeen.has(caller);const c=classify(event,this.discoverySeen.get(caller));event.classification=c.classification;event.classificationReasons=c.reasons;this.events.unshift(event);if(this.events.length>MAX_EVENTS)this.events.length=MAX_EVENTS;if(event.realUse){this.real.push(event);this.persistReal()}this.persist();return event}
 snapshot(){const external=this.events.filter(e=>e.external);const real=this.real.filter(e=>e.external);const credible=[];const seen=new Set();for(const e of real){if(e.classification==='CREDIBLE_REAL_USE'&&!seen.has(e.caller)){seen.add(e.caller);credible.push(e)}}const milestones=Array.from({length:10},(_,i)=>credible[i]?{number:i+1,achieved:true,...credible[i]}:{number:i+1,achieved:false});const candidates=real.map(e=>({at:e.at,caller:e.caller,source:e.source,channel:e.channel,classification:e.classification||'UNKNOWN_MACHINE',reasons:e.classificationReasons||['historical evidence insufficient'],audit:e.audit||null}));return {service:'RECOVER',generatedAt:new Date().toISOString(),external:{calls:external.length,uniqueCallers:new Set(external.map(e=>e.caller)).size,mcpCalls:external.filter(e=>e.kind==='mcp').length,recoverCalls:external.filter(e=>e.kind==='recover').length},realUse:{allTimeCalls:real.length,allTimeCallers:new Set(real.map(e=>e.caller)).size,allTimeVerifiedStrangers:credible.length},realWorldConversionMilestones:milestones,candidateRealUse:candidates,verificationPolicy:{version:2,rule:'Core-tool invocation is evidence of use, not automatically evidence of a real stranger. Only CREDIBLE_REAL_USE advances stranger milestones.',classes:['KNOWN_VALIDATOR','LIKELY_VALIDATOR','CONTROLLED_TEST','UNKNOWN_MACHINE','CREDIBLE_REAL_USE'],historicalEventsDefault:'UNKNOWN_MACHINE'},persistence:{enabled:this.persistent,realUseFile:this.persistent?this.realFile:null,realUseCapacity:'unbounded'},privacy:{rawIpStored:false,requestPayloadStored:false,fullSensitiveTargetUrlStored:false},realFeed:[...real].reverse().slice(0,500),feed:external.slice(0,100)}}
}
