import http from 'node:http';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import {decide} from './engine.js';
import {handle,MCP_PROTOCOL_VERSION} from './mcp.js';
import {ActivityStore} from './activity.js';
export const VERSION='0.1.2';
const activity=new ActivityStore();
const headers={'x-content-type-options':'nosniff','x-frame-options':'DENY','referrer-policy':'no-referrer','cache-control':'no-store'};
function send(res,status,body,extra={}){const text=JSON.stringify(body);res.writeHead(status,{'content-type':'application/json; charset=utf-8','content-length':Buffer.byteLength(text),...headers,...extra});res.end(text)}
async function body(req,max=32768){let n=0,parts=[];for await(const c of req){n+=c.length;if(n>max)throw new Error('body too large');parts.push(c)}if(!parts.length)return{};return JSON.parse(Buffer.concat(parts).toString('utf8'))}
function persistenceDir(){return process.env.RECOVER_DATA_DIR??(process.env.RAILWAY_ENVIRONMENT?'/data':path.resolve('.recover-data'))}
function touchPersistenceSentinel(){const dir=persistenceDir();const file=path.join(dir,'persistence-sentinel.json');let prior=null;try{prior=JSON.parse(fs.readFileSync(file,'utf8'))}catch{}const now=new Date().toISOString();const state={id:prior?.id||crypto.randomUUID(),createdAt:prior?.createdAt||now,lastStartedAt:now,restartCount:Number(prior?.restartCount||0)+1};try{fs.mkdirSync(dir,{recursive:true});const tmp=`${file}.${process.pid}.tmp`;fs.writeFileSync(tmp,JSON.stringify(state),{mode:0o600});fs.renameSync(tmp,file);return {...state,persistent:true,proven:state.restartCount>=2}}catch{return {...state,persistent:false,proven:false}}}
const persistenceSentinel=touchPersistenceSentinel();
function page(){return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>RECOVER Activity</title><style>body{font-family:system-ui;background:#0b1020;color:#eef2ff;padding:32px}.wrap{max-width:1100px;margin:auto}.muted{color:#9ca3af}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:12px}.box{background:#11172a;border:1px solid #28304d;border-radius:16px;padding:18px}.box.done{border-color:#3c8a62}.big{font-size:30px;font-weight:900}.ok{color:#79f2a7}.wait{color:#9ca3af}h1,h2{margin-top:0}</style></head><body><div class="wrap"><h1>RECOVER Machine Activity</h1><p class="muted">Permanent real-use ledger. Discovery traffic cannot erase stranger milestones.</p><div class="grid" style="margin:24px 0"><div class="box"><div class="muted">All-time real use</div><div class="big" id="real">—</div></div><div class="box"><div class="muted">Converted strangers</div><div class="big" id="conv">—</div></div><div class="box"><div class="muted">Unique real callers</div><div class="big" id="callers">—</div></div></div><div class="box"><h2>FIRST 10 REAL-WORLD STRANGER CONVERSIONS</h2><div id="slots" class="grid"></div></div></div><script>async function load(){const r=await fetch('/v1/activity');const d=await r.json();real.textContent=d.realUse.allTimeCalls;conv.textContent=d.realUse.allTimeConvertedRealWorldCallers;callers.textContent=d.realUse.allTimeCallers;slots.innerHTML=d.realWorldConversionMilestones.map(x=>'<div class="box '+(x.achieved?'done':'')+'"><b>STRANGER #'+x.number+'</b><div class="big '+(x.achieved?'ok':'wait')+'">'+(x.achieved?'✓ ACHIEVED':'WAITING')+'</div>'+(x.achieved?'<div class="muted">'+(x.source||'outside')+' / '+(x.channel||'—')+' · '+(x.caller||'').slice(0,8)+'</div>':'')+'</div>').join('')}load();setInterval(load,15000)</script></body></html>`}
const server=http.createServer(async(req,res)=>{res.setHeader('x-request-id',req.headers['x-request-id']||crypto.randomUUID());const u=new URL(req.url,'http://recover.local');try{if(req.method==='GET'&&u.pathname==='/health')return send(res,200,{ok:true,service:'RECOVER',version:VERSION});if(req.method==='GET'&&u.pathname==='/version')return send(res,200,{service:'RECOVER',version:VERSION});if(req.method==='GET'&&u.pathname==='/v1/activity')return send(res,200,activity.snapshot());if(req.method==='GET'&&u.pathname==='/_internal/persistence'){if(String(req.headers['x-recover-internal']||'')!=='1')return send(res,404,{error:'Not found'});return send(res,200,{service:'RECOVER',version:VERSION,...persistenceSentinel,strangerCount:activity.snapshot().realUse.allTimeConvertedRealWorldCallers})}if(req.method==='GET'&&u.pathname==='/demo'){const input={method:'POST',status:503,error:'upstream timeout',attempt:1,sideEffect:true,idempotencyKey:false};const out=decide(input);const snap=activity.snapshot();return send(res,200,{demo:true,recorded:false,input,result:out,strangerCount:snap.realUse.allTimeConvertedRealWorldCallers,note:'Built-in DEMO is deliberately excluded from analytics and stranger milestones.'})}if(req.method==='GET'&&u.pathname==='/activity'){const html=page();res.writeHead(200,{'content-type':'text/html; charset=utf-8',...headers});return res.end(html)}if(req.method==='GET'&&u.pathname==='/')return send(res,200,{name:'RECOVER',version:VERSION,tagline:'A failed machine action happened. Decide the safest next step.',recover:'POST /v1/recover',demo:'GET /demo',mcp:'POST /mcp',decisions:['RETRY_NOW','WAIT','REPAIR_REQUEST','VERIFY_FIRST','ESCALATE','ABORT']});if(req.method==='POST'&&u.pathname==='/v1/recover'){const input=await body(req);const out=decide(input);activity.record(req,{kind:'recover',decision:out.decision,status:200});return send(res,200,out)}if(u.pathname==='/mcp'){if(req.method!=='POST')return send(res,405,{error:'Use POST'},{allow:'POST'});const message=await body(req,65536);const reply=await handle(message);const route=message?.method==='tools/call'?`tools/call:${String(message?.params?.name||'unknown')}`:message?.method||null;activity.record(req,{kind:'mcp',route,decision:reply?.result?.structuredContent?.decision||null,status:reply===null?202:200});if(reply===null){res.writeHead(202,{...headers,'mcp-protocol-version':MCP_PROTOCOL_VERSION});return res.end()}return send(res,200,reply,{'mcp-protocol-version':MCP_PROTOCOL_VERSION})}return send(res,404,{error:'Not found'})}catch(e){return send(res,400,{error:e instanceof Error?e.message:'Bad request'})}});
if(process.argv[1]&&new URL(import.meta.url).pathname===process.argv[1]){server.listen(Number(process.env.PORT||8080),process.env.HOST||'0.0.0.0',()=>console.log(`RECOVER ${VERSION} listening`))}
export {server};
